In [2]:
import numpy as np
import cv2
import os

In [3]:
IMG_DIR = '../Telegram_Scraper/photos'
FIXED_SIZE = (100, 100)  # Define a fixed size for all images

# Initialize a list to collect image arrays
all_images = []

for img in os.listdir(IMG_DIR):
    img_path = os.path.join(IMG_DIR, img)
    img_array = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    
    if img_array is None:
        print(f"Warning: Unable to read image {img_path}. Skipping.")
        continue

    # Resize the image to the fixed size
    img_array = cv2.resize(img_array, FIXED_SIZE)

    img_array = img_array.flatten()
    img_array = img_array.reshape(1, -1)
    print(img_array)

    all_images.append(img_array)

# Concatenate all image arrays vertically
if all_images:
    all_images = np.vstack(all_images)
    with open('imageoflobeli.csv', 'wb') as f:
        np.savetxt(f, all_images, delimiter=',')
else:
    print("No valid images found to write to CSV.")

[[184 183 178 ...  56  52  54]]
[[118 118 118 ... 118 118 118]]
[[255 255 255 ...  36  36  36]]
[[ 55  55  56 ... 219 219 214]]
[[118 118 118 ... 118 118 118]]
[[ 44  44  44 ... 255 255 255]]
[[ 36  36  37 ... 255 255 255]]
[[120 122 124 ...  92  91  91]]
[[192 192 192 ... 201 201 201]]
[[120 122 124 ...  92  91  91]]
[[254 254 254 ... 103 103 103]]
[[99 99 99 ... 99 99 99]]
[[ 24  24  24 ... 255 255 255]]
[[23 23 23 ... 25 25 25]]
[[227 226 230 ... 105 105 107]]
[[13 13 13 ... 13 13 13]]
[[155 155 155 ... 254 254 254]]
[[255 255 255 ... 255 255 255]]
[[11 11 11 ... 18 18 18]]
[[ 44  44  44 ... 255 255 255]]
[[255 255 255 ... 255 255 255]]
[[ 30  30  30 ... 185 185 185]]
[[13 13 13 ... 13 13 13]]
[[ 38  39  40 ... 237 237 237]]
[[70 70 70 ... 30 30 30]]
[[13 13 13 ... 52 44 26]]
[[ 13  13  13 ... 246 246 246]]
[[199 152  91 ...  21  29  33]]
[[240 240 240 ... 165 165 167]]
[[13 13 13 ... 13 13 13]]
[[ 13  13  13 ... 254 255 255]]
[[240 241 241 ... 243 243 240]]
[[255 255 255 ... 204 20